version: '2'

services:
  nginx:
    container_name: nginx-dc
    image: nginx
    build: ./nginx
    links:
      - was-1:was-1
      - was-2:was-2
      - was-3:was-3
    ports:
      - 80:80
    depends_on:
      - was-1
      - was-2
      - was-3
    restart: always

  was-1:
    container_name: node-dc-1
    image: node-was
    ports:
      - 3000
    volumes:
      - ./:/src
      - ./node_modules:/src/node_modules

  was-2:
    container_name: node-dc-2
    image: node-was
    ports:
      - 3000
    volumes:
      - ./:/src
      - ./node_modules:/src/node_modules

  was-3:
    container_name: node-dc-3
    image: node-was
    ports:
      - 3000
    volumes:
      - ./:/src
      - ./node_modules:/src/node_modules